### ISSUE TITLE
giving different results with the same vector values.

### ISSUE THREAD

**Issue by abdallahbouhannache** [bohnacker/p5js-screenPosition#1]
i have used your code of getting the screenX and y positions but instead of giving me the same result for the same X,Y,Z ? 
the way i implemented the code is i used only the addScreenPositionFunction function 
so what seems to be the issue ?thanks

**Comment by bohnacker** [comment]
Hi @abdallahbouhannache, 
can you please show me the code of what you're doing? Best would be to put your example on https://editor.p5js.org/ and share the link. 

But generally speaking: it's quite usual to get different results for the same x, y, z values, because any time you make a transformation (translate, scale, rotate, ...) the result will be different.

An example in 2D mode:
```javascript
var p1 = screenPosition(0, 0);
translate(100, 200);
var p2 = screenPosition(0, 0);
```
p1 will be `{x: 0, y: 0}`
p2 will be `{x: 100, y: 200}`
